// <auto-generated />
using Fociwebapp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fociwebapp.Migrations
{
    [DbContext(typeof(FociDBcontext))]
    [Migration("20240916113240_sqlite.local_migration_346")]
    partial class sqlitelocal_migration_346
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Fociwebapp.Models.Meccs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fordulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HazaiFel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HazaiNev")
                        .HasColumnType("TEXT");

                    b.Property<int>("HazaiVeg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendegFel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendegNev")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendegVeg")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Meccsek");
                });
#pragma warning restore 612, 618
        }
    }
}
